#!/usr/bin/sh
rm -r doc js

echo COMPILE
coffee  --compile --output js src

echo LINT
coffeelint -f script/lintConfig.json src/*.coffee src/*/*.coffee

echo DOCUMENT
mkdir doc doc/project
script/NaturalDocs-1.52/NaturalDocs \
	--input src \
	--output HTML doc \
	--project doc/project \
	--rebuild


